export const REQUEST_ADD_TO_CART = "REQUEST_ADD_TO_CART";
export const SUCCESS_ADD_TO_CART = "SUCCESS_ADD_TO_CART";
export const FAIL_ADD_TO_CART = "FAIL_ADD_TO_CART";
export const SHOW_ADD_TO_CART = "SHOW_ADD_TO_CART";

export const REQUEST_REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SUCCESS_REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const FAIL_REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const REQUES_SAVE_SHIPPING_INFO = "REQUES_SAVE_SHIPPING_INFO";
export const SUCCESS_SAVE_SHIPPING_INFO = "SUCCESS_SAVE_SHIPPING_INFO";
export const FAIL_SAVE_SHIPPING_INFO = "FAIL_SAVE_SHIPPING_INFO";

export const REQUES_SHOW_SHIPPING_INFO = "REQUES_SHOW_SHIPPING_INFO";
export const SUCCESS_SHOW_SHIPPING_INFO = "SUCCESS_SHOW_SHIPPING_INFO";
export const FAIL_SHOW_SHIPPING_INFO = "FAIL_SHOW_SHIPPING_INFO";


export const CLEAR_ERRORS = "CLEAR_ERRORS"