export const ORDER_REQUEST = "ORDER_REQUEST"
export const ORDER_SUCCESS = "ORDER_SUCCESS"
export const ORDER_FAIL = "ORDER_FAIL"

export const ORDER_HISTORY_REQUEST = "ORDER_HISTORY_REQUEST"
export const ORDER_HISTORY_SUCCESS = "ORDER_HISTORY_SUCCESS"
export const ORDER_HISTORY_FAIL = "ORDER_HISTORY_FAIL"

